### ISSUE TITLE
[Test] Getting 2 failures when running specs on local environment

### ISSUE THREAD

**Issue by gnomonunes** [AgileVentures/LocalSupport#471]
I'm getting these two failures when running `bundle exec rake spec` on my local environment:

```
1) Doit::PostToDoit.call create a volunteer op in Doit
   Failure/Error: http_adapter.post("#{ENV['DOIT_HOST']}#{doit_volonteer_op_resource}", options)
   
   WebMock::NetConnectNotAllowedError:
     Real HTTP connections are disabled. Unregistered request: POST http:///opportunities with body '{"advertise_start_date":"2017-01-01","advertise_end_date":"2017-03-01","blurb":"Some nice people","description":"Some nice people","owner_recruiter_id":"4dd7dfe2-c281-4170-8f0b-da17e8af5e5d","locations":[{"address":null,"postcode":null,"location_type":"SL","lat":51.5676116,"lng":-0.3580085}],"title":"Help out"}' with headers {'Content-Type'=>'application/json', 'X-Api-Key'=>'dummy_token'}
   
     You can stub this request with the following snippet:
   
     stub_request(:post, "http:///opportunities").
       with(:body => "{\"advertise_start_date\":\"2017-01-01\",\"advertise_end_date\":\"2017-03-01\",\"blurb\":\"Some nice people\",\"description\":\"Some nice people\",\"owner_recruiter_id\":\"4dd7dfe2-c281-4170-8f0b-da17e8af5e5d\",\"locations\":[{\"address\":null,\"postcode\":null,\"location_type\":\"SL\",\"lat\":51.5676116,\"lng\":-0.3580085}],\"title\":\"Help out\"}",
            :headers => {'Content-Type'=>'application/json', 'X-Api-Key'=>'dummy_token'}).
       to_return(:status => 200, :body => "", :headers => {})
   
     registered request stubs:
   
     stub_request(:post, "http://api.qa2.do-it.org/v2/opportunities")
     stub_request(:any, "/maps\.googleapis\.com/")
   
     ============================================================
   # ./app/services/doit/post_to_doit.rb:22:in `call'
   # ./app/services/doit/post_to_doit.rb:13:in `call'
   # ./spec/services/doit/post_to_doit_spec.rb:13:in `block (3 levels) in <module:Doit>'

2) Doit::GetManagedOrganisations.call returns list of managed organisation from Doit
   Failure/Error: response = http.get("#{ENV['DOIT_HOST']}#{organisations_resource}", options)
   
   WebMock::NetConnectNotAllowedError:
     Real HTTP connections are disabled. Unregistered request: GET http:///users/current/orgs with headers {'X-Api-Key'=>'dummy_token'}
   
     You can stub this request with the following snippet:
   
     stub_request(:get, "http:///users/current/orgs").
       with(:headers => {'X-Api-Key'=>'dummy_token'}).
       to_return(:status => 200, :body => "", :headers => {})
   
     registered request stubs:
   
     stub_request(:get, "http://api.qa2.do-it.org/v2/users/current/orgs?page=2")
     stub_request(:get, "http://api.qa2.do-it.org/v2/users/current/orgs?page=1")
     stub_request(:any, "/maps\.googleapis\.com/")
   
     ============================================================
   # ./app/services/doit/get_managed_organisations.rb:42:in `block in each'
   # ./app/services/doit/get_managed_organisations.rb:41:in `loop'
   # ./app/services/doit/get_managed_organisations.rb:41:in `each'
   # ./app/services/doit/get_managed_organisations.rb:30:in `find_all_across_pages'
   # ./app/services/doit/get_managed_organisations.rb:16:in `call'
   # ./app/services/doit/get_managed_organisations.rb:12:in `call'
   # ./spec/services/doit/get_managed_organisations_spec.rb:13:in `block (3 levels) in <module:Doit>'
```

Some information about my environment:
Platform: macOS Sierra 10.12.6
Ruby version: 2.3.1p112 (2016-04-26 revision 54768) [x86_64-darwin16] (using rbenv)
Bundler version: 1.15.4

**Comment by tansaku** [comment]
I think you might just need ```DOIT_HOST: 'http://api.qa2.do-it.org/v2'``` in `config/application.yml` - if that fixes it we need to update the install instructions

**Comment by tansaku** [comment]
@Maroo-b ^^^
